pipeline{
    agent { label 'verify' }
    post {
        always{
            mail bcc: '', body: 'dea all', 
            cc: 'anthony.tian@cixtech.com, peter.chen@cixtech.com, peter.zhang@cixtech.com', 
            from: 'devops@cixcomputing.com', replyTo: '', 
            subject: 'Lab loader finished', 
            to: 'anthony@cix.com'
        }
    }
    parameters {
        file(name: 'non_default_flash_fw',
        description: 'Usually this argment should NOT be used. If you have special requirements to firmware, upload the selected non_default flash firmware like cix_flash_all.bin here.')
        choice(name: 'as_default', choices: ['No', 'Yes'], 
        description: 'Whether to update the uploaded FW as default firmware.')
    }
    environment {
        SH_UFW = "$params.non_default_flash_fw"
        SH_ADF = "$params.as_default"
        SH_JBN = "${JOB_BASE_NAME}"
    }
    stages {
        stage('FW Flashing') {
            steps{
                echo 'This is Firware Flashing step'
                sh '''
                pname=`echo $SH_JBN | cut -d'_' -f-1 | tr A-Z a-z`
                lab_loader/fpga/swflash.py $pname $SH_UFW $SH_ADF
                '''
            }
        }
    }
}
