pipeline{
    agent { label 'verify' }
    post {
        always{
            script{
                publishHTML (target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: '/home/jackeydu/jenkins/workspace/report/',
                    reportFiles: 'reports.html',
                    reportName: "brom-test-report"
                ])
            }
        }
    }
    parameters {
        choice(name: 'Model', choices: ['AP', 'BROM'], description: 'Test Model¡­.')
    }
    environment {
        SH_MODEL = "$params.Model"
    }
    stages {
        stage('SCA') {
            steps{
                echo 'This is SCA step' 
            }
        }
        stage('Deploy') {
            steps{
                echo 'This is Deploy step'
            }
        }
        stage('jobGen') {
            steps{
                echo 'This is jobGen step'    
            }
        }
        stage('jobRun') {
            steps{
                echo 'This is jobRun step'
                sh '''
                ./run.sh $SH_MODEL
                '''
            }
        }
    }
}
